export type Team = {
    _id: string,
    name: string,
    tla: string,
    crest: string,
    teamColor: string,
    baseCity: string,
    establish: string,
    homeStadium: string,
    players: string[],
    maxNumber: number,
    createdAt: string,
    updatedAt: string,
    coach: string,
}